### ISSUE TITLE
Nested Struct support

### ISSUE THREAD

**Issue by damianoneill** [anjmao/go2proto#5]
Thanks, @anjmao for the tool.  Appreciate you taking the time to create it.  

Would be great, to include support for Nested Structs, for e.g. 

```go
// Authentication - Collection type for Auth options
type Authentication struct {
	Password struct {
		Password *string `json:"password"`
		Username *string `json:"username"`
	} `json:"password,omitempty" yaml:"password,omitempty"`
}
```

Results in 

```proto
message Authentication {
  struct{Password *string "json:\"password\""; Username *string "json:\"username\""} password = 1;
} 
```

**Comment by anjmao** [comment]
Hi @damianoneill

Personally I don't like nested structs because initialisation is quite verbose and you need to repeat inner struct fields.

```go
auth := Authentication {
	Password: struct {
		Password *string `json:"password"`
		Username *string `json:"username"`
	} {
		Password: nil,
		Username: nil,
	},
}
```
 Could be

```go
type Password struct {
	Password *string `json:"password"`
	Username *string `json:"username"`
}
type Authentication struct {
	Password Password `json:"password,omitempty" yaml:"password,omitempty"`
}

auth := Authentication{
	Password: Password{
		Password: nil,
		Username: nil,
	},
}
```

P.S In your example it's a bit strange that you put Username under nested Password struct. I recommend to keep it simple

```go
type Authentication struct {
	Password *string `json:"password"`
	Username *string `json:"username"`
}
```

But for sure this is a valid use case. Thanks for suggestion.

**Comment by damianoneill** [comment]
Thanks @anjmao I appreciate the response.  I don't disagree with your views, however.  

The structure is defined by a third party in a JSON payload, I have no control over the API or the naming/definitions of nested objects.  

The structures are very large, therefore I use a generator, mholts JSON to Go to generate the structs, unfortunately, inlining / renaming won't be an option as this is likely to be error-prone.  

Thanks for your time.
Damian.
